version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: autocompany
      POSTGRES_DB: autocompany
      POSTGRES_PASS: autocompany123
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/posgresql/data

  autocompany:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/autocompany
    command: python manage.py runserver 0.0.0.0:8000 --settings=autocompany.settings
    depends_on:
      - db
volumes:
  pgdata: